### ISSUE TITLE
Setting up frontend of the website.

### ISSUE THREAD

**Issue by utkarsh2102** [GlobalTechTalks/AbsoluteHacks#4]
The task is to set up all the required dependencies before starting the actual project.
Be it the SEOs or whatever.
Just set up `index.html` and the related dependencies.

**Comment by AniVerma17** [comment]
I can take it.

**Comment by utkarsh2102** [comment]
Awesome @AniVerma17.
Please make a PR at the earliest.

**Comment by utkarsh2102** [comment]
Closing this.
Thanks @AniVerma17.
